" Vim 7 configuration file

" Install packages
call plug#begin()
Plug 'tpope/vim-fugitive'
Plug 'kien/ctrlp.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'justinmk/vim-dirvish'
Plug 'sickill/vim-monokai'
Plug 'pangloss/vim-javascript'
Plug 'ternjs/tern_for_vim'
Plug 'tpope/vim-surround'
Plug 'ajh17/VimCompletesMe'
call plug#end()

filetype plugin indent on
syntax enable
set nocompatible
let mapleader = " "

set encoding=utf-8
set completeopt=menu,preview,longest
set backspace=2
set ttyfast
set modelines=0
set history=500
set autoread
set showmatch
set backspace=indent,eol,start
set laststatus=2
set splitbelow splitright

set statusline=%<\ %F%=\ %{&fileformat}\ \|\ %{&fileencoding}\ \|\ %{&filetype}\ \|\ %p%%\ \|\ LN\ %l:%c\ 
" Fonts and Colours
set guifont=Sauce\ Code\ Powerline:h12
" 100 characters wide column
set colorcolumn=100

" User Interface
colorscheme monokai 
set background=dark

if has("gui_running")
  set guioptions-=m " no menu
  set guioptions-=T " no toolbar
  set guioptions-=r " no scrollbar on the right
  set guioptions-=L " no scrollbar on the right
  set guioptions-=b " no scrollbar on the bottom
endif

set title
set number
set cursorline
set ruler
set scrolloff=3
set showcmd
set lazyredraw
set hidden
set showmode
set wildmenu
set wildmode=list:longest

" Files and Backups
set nobackup
set nowritebackup
set noswapfile
set backupdir=~/tmp,/tmp
set undodir=~/.vim/.tmp,~/tmp,~/.tmp,/tmp
set wildignore=.svn,CVS,.git,*.swp,*.jpg,*.png,*.gif,*.pdf,*.bak
set suffixes+=.old
set undofile

" Text Formatting
set smartcase
set ignorecase
set incsearch
set hlsearch
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab
set nowrap

" Keybindings

  " General Keybindings
  imap jk <ESC>
  nnoremap <backspace> <C-^>
  nnoremap ` '
  nnoremap ' `
  imap <C-s> <C-o>:w!<CR>
  imap <C-v> <ESC>"+gP
  vmap <C-c> "+y
  nnoremap / /\v
  map \ :Dirvish<cr>

  " Menu settings
  inoremap <expr><Esc>      pumvisible() ? "\<C-e>" : "\<Esc>"
  inoremap <expr><CR>       pumvisible() ? "\<C-y>" : "\<CR>"
  inoremap <expr><C-j>      pumvisible() ? "\<C-n>" : "\<C-j>"
  inoremap <expr><C-k>      pumvisible() ? "\<C-p>" : "\<C-k>"
  autocmd CompleteDone * pclose

  " Window bindings
  nnoremap <leader>wh <C-w>h
  nnoremap <leader>wj <C-w>j
  nnoremap <leader>wk <C-w>k
  nnoremap <leader>wl <C-w>l
  nnoremap <leader>wo <C-w>o
  nnoremap <leader>wc <C-w>c
  nnoremap <leader>ws <C-w>s
  nnoremap <leader>wv <C-w>v

  " Buffer bindings
  map <tab> :bn!<CR>
  map <S-tab> :bp!<CR>
  nmap <leader>bd :bp<bar>sp<bar>bn<bar>bd<CR>
  nmap <leader>bb :buffers<cr>
  nmap <leader>bn :bn!<CR>
  nmap <leader>bp :bp!<CR>

  nmap <leader>qq :wqa!<CR>
  nmap <leader><Esc> :q!<CR>
  nmap <leader>/ :noh<CR>

  nmap <leader>ff :edit 
  nmap <leader>fs :w!<CR>
  nmap <leader>feR :source ~/.vimrc
  nmap <leader>fed :edit ~/.vimrc<CR>

  " Tab Management
  nnoremap <leader>tn :tabn<cr>
  nnoremap <leader>tp :tabp<cr>

  
